[tool.poetry]
name = "catchment"
version = "1.0.0"
description = "Analyse river catchment data"
authors = ["Alex Ridell"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^2.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
